### ISSUE TITLE
Speed test of this vs scallion or eschalot

### ISSUE THREAD

**Issue by james-see** [wybiral/onions#1]
I was able to do some preliminary tests with eschalot. So far, I can gen. results on macOS about 10x faster using Eschalot vs this. I've only repeated a few times though, so def not enough for a good sample.

**Comment by wybiral** [comment]
This script was written for simplicity rather than to compete with the top generators out there. Take a look at something like [scallion](https://github.com/lachesis/scallion), which uses OpenCL to boost performance (my guess is that it vastly outperforms this). Even better, you could massively distribute your search across a cluster.

But, in terms of simplicity and readability I think this one wins. If you have any interest in forking this and doing a performance rewrite, I'd be interested, but that's not the real goal here.

**Comment by james-see** [comment]
@wybiral I see, I stupidly though "oooh go, must be very fast" since I am myself trying to port most of my python 3 code for scripts to go. Also, I don't have a lot of cuda lying around but I have 12 cores, so thought eschalot would be a good fit. Good to know and yes the code is super clean. Nice work.

**Comment by wybiral** [comment]
@jamesacampbell, thanks. Go is usually pretty fast, but naturally it depends on how it's being used. In order to get the same kind of performance here someone would have to custom-implement some of these standard methods instead of calling them as-is.

In theory, even Python could perform about the same as this so long as the external methods being relied on were optimized enough. Go shines more when you have to actually implement the performance critical parts (especially when concurrency or networking are involved).
